### ISSUE TITLE
Version file and CKAN integration

### ISSUE THREAD

**Issue by mheguy** [Crzyrndm/RW-Saturatable#4]
`SaturatableRW.version` indicates the most recent release `1.10.3` is compatible with `1.0.0` and not `1.1.0`. This is leading CKAN to report the same.

I can put an override into the CKAN metadata for this version if it is indeed `1.1.0` compatible.

**Comment by Crzyrndm** [comment]
I'll just fix the version file when I get home tonight. Silly things happen when you need to update this many things -.-

**Comment by mheguy** [comment]
I know that feeling only too well. KSP releases make for an interesting time when indexing hundreds of mods. =)

I'll leave this open in case you're using it as a reminder, but of course close it at your leisure.

**Comment by Crzyrndm** [comment]
Should now be fixed
